### ISSUE TITLE
Counter-Strike is a game developed by valve

### ISSUE THREAD

**Issue by avslav** [Chanakan5591/text2bin#1]
COUNTER STRIKE GLOBAL OFFENSIVE IS A GAME DEVELOPED BY VALVE
it is extremely difficult considering you have to wrangle your teammates
manage your economy
predit your enemie's economy
buy the correct shit
then aim for the head and spray correctly

you have to be really good with your mouse
there is a story, that someone was so good with his mouse
he became the mouse
the mouse permanently fused into his hand
now he has to use his other hand for certain things

the game has so many fun maps 
like dust 2 
which is the only map
and mirage
but mirage just really isnt working these days

you can play as the terrorists
and blow shit up while praising the only god
or you can play as the counter terrorists
who counter the terrorists
terrorizing terrorism

the game will bring you so many fun experiences
such as playing a game with aldon hilter
as he only buys a negev
and unpolitely refuses to buy anything else

this game has multiple guns
the deagle, the ak47, the p90, the awp and the most dangerous and the deadliest of all
tHe dEcOy gReNadE
not many people know but the decoy grenade is sent from the deepest circle of hell where the souls of the damned are burned and seared alive for all eternity

on your journey to become better in this game
you wil encounter smurfs
non bilingual russians
toxicity
mute people
people that make you realise csgo causes metaphysical retardation
or atleast will make you being true

but the worst of all
people who try nice try after you fucking fail your shitty clutch attempt

there are a lot of mods for this game
like bunny hopiing servers, 1v1 servers, tdm servers jailbreak and a lot of others too

oh i almost forgot to mention the skins
every single gun can be cosmetically customised if you have the money
this game has multiple skins
ranging from your generic pistol skin
to a 1600 dollar knife skin

its a great game
its also perfectly fucking free
SO GO GET IT!!!

**Comment by Chanakan55991** [comment]
ur mom

**Comment by avslav** [comment]
> ur mom

our mom
